version: '3'
services:
  api:
    command: npm run start
    build: .
    volumes:
      - ./api:/app
    links:
      - mongo
    networks:
      - backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}

networks:
  backend:
    driver: bridge